# Lucy

hide_ascii      = true
spacing         = 2
padding         = 0
 separator       = " ● "
# separator = " 󰁙 "
# separator = " 󰁖 "
key_color       = "#8AADF4"
separator_color = "#ED8796"

[bar]
glyph           = "●"
symbol_open     = "("
symbol_close    = ")"
hide_delimiters = true
visible         = false

[box]
title           = " Lucy "
border          = "rounded"
visible         = true

[box.inner_margin]
x               = 2
y               = 1

[custom_ascii]
color           = "#8cabee"

[randomize]
key_color       = false
separator_color = false

[keys]
#host            = "󰌢 Host"
#kernel          = "󰌽 Kernel"
#battery         = "󰁹 Battery"
#os              = "󰌽 OS"
#de              = "󰍹 DE"
#wm              = "󰍹 WM"
#distro          = "󰣇 Distro"
#terminal        = "󰆍 Terminal"
#shell           = "󱆃 Shell"
#packages        = "󰏗 Packages"
#uptime          = "󱑓 Uptime"
#memory          = "󰍛 Memory"
#machine         = "󰌢 Machine"
#local_ip        = "󰩟 IP"
#backlight       = "󰃠 Brightness"
#resolution      = "Resolution"
#cpu_load        = "󰻠 CPU Load"
#cpu             = "󰻠 CPU"
#gpu             = "󰢮 GPU"
#disk_space      = "󰋊 Disk Space"
host            = " Host"
kernel          = " Kernel"
battery         = " Battery"
os              = " OS"
de              = " DE"
wm              = " WM"
distro          = " Distro"
terminal        = " Terminal"
shell           = " Shell"
packages        = " Packages"
uptime          = "⏻ Uptime"
memory          = " Memory"
machine         = " Machine"
local_ip        = "󰩟 IP"
backlight       = " Brightness"
resolution      = " Resolution"
cpu_load        = "󰻠 CPU Load"
cpu             = "󰻠 CPU"
gpu             = "󰢮 GPU"
disk_space      = " Disk Space"
