#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

# bspc config border_width         2
# bspc config window_gap          12

bspc config border_width         2
bspc config window_gap           5
bspc config top_padding          0
bspc config bottom_padding       0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc config focused_border_color     "#26F0F1"
bspc config focused_border_color     "#5C6F7B"
bspc config normal_border_color      "#202A25"

# starting wallpaper manager
~/.fehbg &
picom &

# start nm-applet
nm-applet &

# starting polybar
$HOME/.config/polybar/launch.sh

# keyboard layout
setxkbmap -layout us,az ,, -option grp:win_space_toggle

# disable touchpad
xinput disable "SynPS/2 Synaptics TouchPad"

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
