#!/usr/bin/env python

import os

home_directory = os.path.expanduser("~")
template = '[Desktop Entry]\nVersion=1.0\nType=Application\nTerminal=false'

name = input("App name: ")
comment = input("Comment: ")
icon = input("Icon: ")
exec = input("Exec: ")

template += '\nName=' + name + '\nExec=' + exec + "\nIcon=" + icon
if comment:
	template += "\nComment=" + comment

f = open(home_directory + "/.local/share/applications/" + name+".desktop", "a")
f.write(template)
f.close()
