#!/usr/bin/env python3

import tkinter as tk
from tkinter import messagebox
import os

home_directory = os.path.expanduser("~")

# Create shortcut
def create():
    # Template for .desktop file
    template = '[Desktop Entry]\nVersion=1.0\nType=Application\nTerminal=false'

    # Entry value
    name = name_entry.get()
    comment = comment_entry.get()
    icon = icon_entry.get()
    exe = exec_entry.get()
    category = categories_entry.get()

    # Adding values to template
    template += '\nName=' + name + '\nExec=' + exe + "\nIcon=" + icon
    if comment:
        template += "\nComment=" + comment
    if category:
        template += "\nCategories=" + category

    # Creating .desktop file
    f = open(home_directory + "/.local/share/applications/" + name+".desktop", "a")
    f.write(template)
    f.close()

    # Alert
    messagebox.showinfo("Success", "Desktop file created succesfully!")

    # Clear entry values
    name_entry.delete(0, tk.END)
    comment_entry.delete(0, tk.END)
    icon_entry.delete(0, tk.END)
    exec_entry.delete(0, tk.END)
    categories_entry.delete(0, tk.END)


# Root
root = tk.Tk()
root.title("Shortcut Creator")
root.geometry("250x550")
root.resizable(False, False)

# App name
title_label = tk.Label(root, text="Shortcut Creator", font=("Arial", 16, "bold"))
title_label.pack(pady=20)

# Separator
separator = tk.Frame(height=2, bd=1, relief=tk.SUNKEN)
separator.pack(fill=tk.X, padx=10, pady=(0, 10), anchor="n")

# Inputs
name_label = tk.Label(root, text="App name:")
name_label.pack(pady=10)
name_entry = tk.Entry(root)
name_entry.pack(pady=5)


comment_label = tk.Label(root, text="Comment:")
comment_label.pack(pady=10)
comment_entry = tk.Entry(root)
comment_entry.pack(pady=5)

icon_label = tk.Label(root, text="Icon:")
icon_label.pack(pady=10)
icon_entry = tk.Entry(root)
icon_entry.pack(pady=5)

exec_label = tk.Label(root, text="Exec:")
exec_label.pack(pady=10)
exec_entry = tk.Entry(root)
exec_entry.pack(pady=5)

categories_label = tk.Label(root, text="Categories:")
categories_label.pack(pady=10)
categories_entry = tk.Entry(root)
categories_entry.pack(pady=5)

# Create Button
submit_button = tk.Button(root, text="Create", command=create)
submit_button.pack(pady=20)

# Main loop
root.mainloop()