#!/usr/bin/env python3

import os

home_directory = os.path.expanduser("~")
template = '[Desktop Entry]\nVersion=1.0\nType=Application\nTerminal=false'

name = input("App name: ")
comment = input("Comment: ")
icon = input("Icon: ")
exe = input("Exec: ")
category = input("Categories: ")

template += '\nName=' + name + '\nExec=' + exe + "\nIcon=" + icon
if comment:
	template += "\nComment=" + comment
if category:
    template += "\nCategories=" + category

f = open(home_directory + "/.local/share/applications/" + name+".desktop", "a")
f.write(template)
f.close()
